Fix missing ipaddr req for fuelweb tests
from ipaddr import IPNetwork :
ImportError: cannot import name IPNetwork

Change-Id: I60bcdb81f285e4b090b66dc1b124eae221e1f257
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>