prepare-build-env: add support for F20 (Heisenbug)
for loop devices:
sudo chroot /home/ignatenko/fuel-main/build/image/centos/SANDBOX python build_centos_image.py -k centos.ks -n centos_65_x86_64 -s "/boot,ext2 /,ext4"
losetup: could not find any free loop device
/usr/lib/python2.6/site-packages/imgcreate/errors.py:40: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return str(self.message)
Error: Failed to loopback mount '/tmp/imgcreate-AWyznm/tmp-iHPgfB/centos_65_x86_64.img' : Failed to allocate loop device for '/tmp/imgcreate-AWyznm/tmp-iHPgfB/centos_65_x86_64.img'

blueprint build-iso-on-fedora
Signed-off-by: Igor Gnatenko <ignatenko@mirantis.com>

Change-Id: If0d487492f7422af5e87d17839df87514396e9f4